#!/usr/bin/env python3
"""Measures Balance vs Vivid Tidewater contrast from the actual stylesheets.

    python3 design/exploration/prototype-vivid/contrast.py   # writes CONTRAST.md

Tokens are parsed from ../prototype/styles.css (.phone and .phone.theme-dark
blocks) and from vivid.css (blocks between the "tokens:" markers); Vivid
inherits every Balance token it doesn't override. Opacity applied by the CSS
(e.g. Balance's ring at 80%) is alpha-blended over the surface it sits on.
WCAG 2.x relative-luminance contrast. Text target 4.5:1; non-text state
graphics (WCAG 1.4.11) 3:1. Liquid Glass areas are excluded (blur-dependent).
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = open(os.path.join(HERE, "..", "prototype", "styles.css")).read()
VIVID = open(os.path.join(HERE, "vivid.css")).read()


def block(css, start_pattern):
    m = re.search(start_pattern + r"\s*\{(.*?)\}", css, re.S)
    return dict(re.findall(r"--([\w]+):\s*(#[0-9A-Fa-f]{6}|rgba?\([^)]*\))", m.group(1)))


base_light = block(BASE, r"\n\.phone(?=\s*\{)")
base_dark = dict(base_light, **block(BASE, r"\.phone\.theme-dark"))
viv_light_over = block(VIVID, r"/\* tokens:light \*/\s*body\.vivid \.phone")
viv_dark_over = block(VIVID, r"/\* tokens:dark \*/\s*body\.vivid \.phone\.theme-dark")
viv_light = dict(base_light, **viv_light_over)
viv_dark = {**base_dark, **viv_light_over, **viv_dark_over}


def rgb(v):
    v = v.strip()
    if v.startswith("#"):
        return tuple(int(v[i:i + 2], 16) for i in (1, 3, 5)), 1.0
    nums = [float(x) for x in re.findall(r"[\d.]+", v)]
    return tuple(int(n) for n in nums[:3]), (nums[3] if len(nums) > 3 else 1.0)


def blend(fg, alpha, bg):
    return tuple(round(f * alpha + b * (1 - alpha)) for f, b in zip(fg, bg))


def lum(c):
    def ch(x):
        x /= 255
        return x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4
    r, g, b = (ch(x) for x in c)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def ratio(a, b):
    la, lb = lum(a), lum(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)


def col(t, name, over=None, alpha=None):
    c, a = rgb(t[name])
    if alpha is not None:
        a = alpha
    if a < 1 and over is not None:
        c = blend(c, a, col(t, over))
    return c


# (label, kind, base(fg,bg,alpha), vivid(fg,bg,alpha)); fg may be a literal colour tuple.
UNDO_BG_BASE = "rgba(127,127,127,.3)"


def measure(t, spec, variant):
    fg, bg, alpha = spec
    bgc = col(t, bg)
    if fg == "UNDO_BG":
        fgc = blend(rgb(UNDO_BG_BASE)[0], .3, col(t, "toastBg"))
        return fgc, bgc
    fgc = col(t, fg)
    if alpha is not None:
        fgc = blend(fgc, alpha, bgc)
    return fgc, bgc


ROWS = [
    ("Tertiary text on card (counts, legends, settling note)", "text", ("ink3", "surface", None), ("ink3", "surface", None)),
    ("Tertiary text on background (eyebrow, section counts)", "text", ("ink3", "bg", None), ("ink3", "bg", None)),
    ("Secondary text on card", "text", ("ink2", "surface", None), ("ink2", "surface", None)),
    ("Accent text on card (pillar value, links)", "text", ("accent", "surface", None), ("accent", "surface", None)),
    ("Text/glyph on accent fill (check, primary button)", "text", ("onAccent", "accent", None), ("onAccent", "accent", None)),
    ("Selected tab label (10 pt) on its highlight", "text", ("accent", "surface2", None), ("accent", "accentSoft", None)),
    ("Recovery text on card", "text", ("recovery", "surface", None), ("recovery", "surface", None)),
    ("Toast text on toast", "text", ("toastInk", "toastBg", None), ("toastInk", "toastBg", None)),
    ("Undo label on Undo button", "text", ("toastInk", "UNDO", None), ("toastUndoInk", "toastUndoBg", None)),
    ("Empty completion ring vs card", "graphic", ("ink3", "surface", .8), ("ring", "surface", None)),
    ("Missed-day ring vs card (ledger)", "graphic", ("ink3", "surface", .7), ("ink3", "surface", None)),
    ("Unfilled weekly pip vs card", "graphic", ("surface2", "surface", None), ("track", "surface", None)),
    ("Done fill vs card", "graphic", ("accent", "surface", None), ("accent", "surface", None)),
    ("Habit icon on icon tile", "graphic", ("accent", "accentSoft", None), ("accent", "accentSoft", None)),
]


def value(t, spec):
    fg, bg, alpha = spec
    if bg == "UNDO":
        undo = blend(rgb(UNDO_BG_BASE)[0], .3, col(t, "toastBg"))
        return ratio(col(t, fg), undo)
    bgc = col(t, bg)
    fgc = col(t, fg)
    if alpha is not None:
        fgc = blend(fgc, alpha, bgc)
    return ratio(fgc, bgc)


def fmt(v, kind):
    need = 4.5 if kind == "text" else 3.0
    return f"{v:.1f}" + ("" if v >= need else " ✗")


lines = ["# Contrast — Balance vs Vivid Tidewater (measured)", "",
         "Generated by `contrast.py` from `../prototype/styles.css` and `vivid.css`. "
         "✗ = below target (text 4.5:1; non-text state graphics 3:1, WCAG 1.4.11). "
         "Opacity is blended over the underlying surface. Liquid Glass areas are excluded.", "",
         "| Pair | Target | Balance light | Vivid light | Balance dark | Vivid dark |", "|---|---|---|---|---|---|"]
fails = {"Balance": 0, "Vivid": 0}
for label, kind, b, v in ROWS:
    bl, vl = value(base_light, b), value(viv_light, v)
    bd, vd = value(base_dark, b), value(viv_dark, v)
    need = 4.5 if kind == "text" else 3.0
    fails["Balance"] += (bl < need) + (bd < need)
    fails["Vivid"] += (vl < need) + (vd < need)
    lines.append(f"| {label} | {need}:1 | {fmt(bl, kind)} | {fmt(vl, kind)} | {fmt(bd, kind)} | {fmt(vd, kind)} |")
lines += ["", f"Pairs below target: Balance {fails['Balance']}, Vivid {fails['Vivid']} (of {len(ROWS) * 2} light+dark checks)."]
open(os.path.join(HERE, "CONTRAST.md"), "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
